stages:
  - test

front-test:
  image: node:16-alpine
  stage: test
  script:
    - cd "$CI_PROJECT_DIR/frontEnd"
    - npm i npm@latest -g
    - npm i
    - npm run test
  only:
    - develop
